galaxy_info:
  role_name: python
  author: Sam Doran
  description: Install Python on macOS
  company:
  license: Apache 2.0
  min_ansible_version: 2.9

  platforms:
    - name: macOS
      versions:
        - all
        - any

  galaxy_tags:
    - development
    - system
    - macos
    - python
