galaxy_info:
  role_name: parallels
  author:
    - Sam Doran
    - Matt Clay
  description: Install Parallels Desktop using the auto deploy package
  company: ~
  license: Apache 2.0
  min_ansible_version: 2.11

  platforms:
    - name: macOS
      versions:
        - any

  galaxy_tags:
    - system
    - virtualization
    - macos

dependencies: []
